name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build and Test
        run: |
          .\mvnw.cmd -q -DskipTests=false test
      - name: Generate JavaDocs (optional)
        run: |
          .\mvnw.cmd -q -DskipTests javadoc:javadoc
